import Head from 'next/head'
import Button from '@/components/button'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className='text'>
          <h1>Corriendo con framework</h1>
        </main>
          <Button></Button>
    </>
  )
}
